Repository rmbolger/Posh-ACME, pull requests merged in 2021-05, with the labels that each got.

#341 Added support for IDN domains in the Simply.com plugin
  Posh-ACME/Plugins/Simply.ps1
Labels: bug, enhancement

#338 Add ukfast dns plugin
  Posh-ACME/Plugins/UKFast-Readme.md
  Posh-ACME/Plugins/UKFast.ps1
Labels: enhancement

#343 Add dedicated Revocation function that supports additional use-cases
  Posh-ACME/Posh-ACME.psd1
  Posh-ACME/Private/Register-ArgCompleters.ps1
  Posh-ACME/Public/Revoke-PACertificate.ps1
Labels: enhancement

#349 Fix Azure plugin to support IMDS within Azure Automation
  Posh-ACME/Plugins/Azure.ps1
Labels: bug

#351 Aurora-Plugin-v2021.0522.1930
  Posh-ACME/Plugins/Aurora-Readme.md
  Posh-ACME/Plugins/Aurora.ps1
Labels: enhancement
